### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by guigrpa** [excalidraw/excalidraw-embed#27]
First of all, thanks for the very useful package!

I'm trying to upgrade from 0.4.x to 0.6.x so that all new Excalidraw goodies are available to [Lobelia Connect](https://connect.lobelia.earth)'s users ;). The build unfortunately breaks due to the fonts missing from the published dist/ folder. Version 0.4.x included them. Maybe something related to the `files` property in `package.json`?

**Comment by dwelle** [comment]
Haven't looked into it, but we'll be publishing a new version soon. In the meantime, you can grab them manually from the [public](https://github.com/excalidraw/excalidraw-embed/tree/master/public) folder

**Comment by ad1992** [comment]
@guigrpa thanks for letting us know. It's fixed in `0.6.1` version.

**Comment by guigrpa** [comment]
Wow, that was fast. Thanks!
