### ISSUE TITLE
Improved Collaboration Support

### ISSUE THREAD

**Issue by Turakar** [excalidraw/excalidraw-embed#28]
**Use Case**
I am currently working on integrating excalidraw with nextcloud via an app. Implementing view/edit functionality was quite easy thanks to this project. To further improve the integration I want to start every excalidraw instance in collaboration mode with a dedicated room per file. This way, users could easily join each others rooms/files and work together, e.g. via link sharing. Nextcloud Talk even adds live chatting this way :slightly_smiling_face:

**Proposal**
Add a `room` property to the Excalidraw component, which - if set - automatically initiates a room connection for collaboration.

**Comment**
I saw that you are currently working on merging excalidraw and excalidraw-embed, so I guess it is better to first wait for this change to happen?

**Comment by dwelle** [comment]
Hello. Currently the idea is to actually start factoring any I/O (localStorage, backend etc.) out from the package so that consumers can implement whatever they wish. It does not make much sense to couple the package to the implementation of our own servers as you wouldn't be able to use them, anyway.

**Comment by Turakar** [comment]
Setting a room URL would be enough as you can host excalidraw-room via the Docker image yourself. But I guess the refactoring you plan is the cleaner way.

**Comment by Turakar** [comment]
> Hello. Currently the idea is to actually start factoring any I/O (localStorage, backend etc.) out from the package so that consumers can implement whatever they wish. It does not make much sense to couple the package to the implementation of our own servers as you wouldn't be able to use them, anyway.

Is there a tracking issue or similar for this where I can get notified if the changes land?

**Comment by dwelle** [comment]
@Turakar there is now, so closing in favor of https://github.com/excalidraw/excalidraw/issues/2213 -- if you have any further ideas, let's chime in there.
