### ISSUE TITLE
Mobile view resolution seems to be not responsive

### ISSUE THREAD

**Issue by damikun** [excalidraw/excalidraw-embed#31]
**Current state:**
- If I install and run latest excalidraw from npm the mobil size resolution seems to not be responsive... I'm attaching some images of it... **Is this known issue of this version?**
- If I check main domain project.. on web (www.excalidraw.com) it seems to be responsive

Is this feature not ported yet or is this a bug?

**What's current state of this?**
- A: Should I build own master  (if it is possible)  and fix it by myself by adjusting styles?
- B: This is known problem and will be updated in next releases?

Thx for any response...

....................................................

**My embeded version**
![image](https://user-images.githubusercontent.com/54806834/97718554-5d886a00-1ac6-11eb-9ea7-df9d7d77bec9.png)

**WebWersion:**
![image](https://user-images.githubusercontent.com/54806834/97718610-6c6f1c80-1ac6-11eb-9782-a8974018a885.png)

**Comment by dwelle** [comment]
Known problem. Current npm package is very out of date and we're working to publish a new one where this should already be fixed.

If you don't want to wait, you can build your own by forking this repo, cd-ing to `src/excalidraw-embed` and running `build:umd` npm script. You'll have to host the package yourself or install directly from your github fork.

**Comment by damikun** [comment]
Super answer exactly what I was looking for.. thx..

**Comment by dwelle** [comment]
It shouldn't be long before we publish the new version so I think it's ok to close.

**Comment by damikun** [comment]
Hi @dwelle any news of release coming for excalidraw-embed ? looks like it is not included in main package of _src_ anymore..

**Comment by ad1992** [comment]
We would probably release once (excalidraw/excalidraw#2313 & some pending items) are done. 
But if you are blocked at it, you can build it by forking  [excalidraw/excalidraw](https://github.com/excalidraw/excalidraw) and publish the package as @dwelle mentioned.
You would have to cd to  `src/packages/excalidraw` and run `build:umd`.
