### ISSUE TITLE
Wrong coordinates when embedded on scrollable page

### ISSUE THREAD

**Issue by vojtaholik** [excalidraw/excalidraw-embed#32]
I would like to embed excalidraw on a page that scrolls, while changing `.excalidraw` position from `fixed` to e.g. `relative`. Result:

![excalidraw](https://user-images.githubusercontent.com/25487857/98644777-469d0f80-2331-11eb-8d46-dab2e640a52f.gif)

[codesandbox](https://codesandbox.io/s/headless-water-g6eh9?file=/src/styles.css)

is this supposed to work or am I missing something?

**Comment by dwelle** [comment]
Haven't checked, but I think we'd have to update container offsets on `body`/`window` scroll event. Not sure if a good idea since it wouldn't catch cases where the excalidraw component is mounted in a non-body scrollable container. @ad1992 thoughts?

Be it as it may, you will be able to handle this yourself soon (when we release [`@excalidraw/excalidraw`](https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw)) by setting the offsets manually.

**Comment by ad1992** [comment]
> Haven't checked, but I think we'd have to update container offsets on `body`/`window` scroll event. Not sure if a good idea since it wouldn't catch cases where the excalidraw component is mounted in a non-body scrollable container. @ad1992 thoughts?
> 
Haven't looked into this yet. But this is a valid use case so will look into this if it can be supported out of the box.

**Comment by farzane1352** [comment]
> Haven't checked, but I think we'd have to update container offsets on `body`/`window` scroll event. Not sure if a good idea since it wouldn't catch cases where the excalidraw component is mounted in a non-body scrollable container. @ad1992 thoughts?
> 
> Be it as it may, you will be able to handle this yourself soon (when we release [`@excalidraw/excalidraw`](https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw)) by setting the offsets manually.

**Comment by farzane1352** [comment]
> > Haven't checked, but I think we'd have to update container offsets on `body`/`window` scroll event. Not sure if a good idea since it wouldn't catch cases where the excalidraw component is mounted in a non-body scrollable container. @ad1992 thoughts?
> 
> Haven't looked into this yet. But this is a valid use case so will look into this if it can be supported out of the box.

**Comment by farzane1352** [comment]
>

**Comment by farzane1352** [comment]
``

**Comment by ad1992** [comment]
@vojtaholik you can try out [@excalidraw/excalidraw](https://www.npmjs.com/package/@excalidraw/excalidraw).
closing this since this library is deprecated so we will fix the issues in the base repo.
