### ISSUE TITLE
isDeleted attributes are not kept when restoring data

### ISSUE THREAD

**Issue by christophepas** [excalidraw/excalidraw-embed#33]
Hey there 👋 

First massive shout out for making Excalidraw usable externally, we're planning to use it for slite.com (collaboration & knowledge base tool), I'm super excited about it. 

I have detected an easy to fix issue: today when reading `initialData`, the component will use the function restore that force `isDeleted` to `false` for each element. 

Very easy way to test this, in the sandbox, simply set `isDeleted` at `true` for an element and you'll see it's not reflected in the canvas after being loaded. 

-> need to read the element attribute 
![image](https://user-images.githubusercontent.com/6739099/98666463-5fb3b980-234d-11eb-803e-8dbd63b5c2a5.png)

**Comment by dwelle** [comment]
Yep, this is already fixed upstream. Not sure if we'll update this package because it will be replaced by [`@excalidraw/excalidraw`](https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw) soon.

**Comment by christophepas** [comment]
Allright awesome then, do you have an idea of the timing for this release? (and if it means the same maintenance as the core package, great idea)

**Comment by dwelle** [comment]
Probably after we finish factoring out I/O (https://github.com/excalidraw/excalidraw/pull/2313 etc.)

**Comment by christophepas** [comment]
Hey @dwelle, I saw the above PR has been merged, are you now officially planning to port the embed component to the master repo? 

In the meantime if it takes a bit of time, if we could just merge the tiny fix above as well, it would be awesome (can't submit PRs but happy to do so of course). 

Cheers!

**Comment by dwelle** [comment]
We are planning to officially port it for some time now. In fact, it's almost entirely done, just finishing up.

Anyway, I've fixed this in `master`, but we'll need to publish (I don't have permissions).

/cc @ad1992 what's our status on `@excalidraw/excalidraw`?

**Comment by ad1992** [comment]
@christophepas @dwelle I have published a version `0.6.3` with this fix. 
We would be releasing the first version of `@excalidraw/excalidraw` this week very soon. 
Just finishing up some pending items before the release.

**Comment by christophepas** [comment]
That's amazing, big thanks to both of you!
