### ISSUE TITLE
Center initial data on load

### ISSUE THREAD

**Issue by andresriveratoro** [excalidraw/excalidraw-embed#34]
I'm encountering an issue where the Excalidraw elements are not centered properly on load. It's centering the elements based on the window size and not Excalidraw's component dimensions.

This is the drawing that is saved to the backend.
<img width="1163" alt="Screen Shot 2020-12-03 at 11 16 03" src="https://user-images.githubusercontent.com/36863582/101056485-052b0900-3559-11eb-9459-20ffffcf2cf3.png">

This is the same drawing when passing it as initialData.
<img width="1163" alt="Screen Shot 2020-12-03 at 11 16 16" src="https://user-images.githubusercontent.com/36863582/101056623-2be93f80-3559-11eb-846b-dd753eeaf38f.png">

If I scroll down and click on "Scroll back to content", the drawing is centered properly.

**Comment by dwelle** [comment]
Yea, this is plaguing us on and off forever. Not sure if it ever worked 100%, but we should definitely take a look :).

**Comment by andresriveratoro** [comment]
Would updating the app state to setAppState({ ...calculateScrollCenter(elements, appState, canvas) }) after the scene has loaded work?

**Comment by dwelle** [comment]
We're already doing that during init in `initializeScene()` (but best to double check). My guess is the `calculateScrollCenter` doesn't work correctly, or we're passing incorrect container dimensions/offsets.

Want to investigate and take this issue on?

**Comment by andresriveratoro** [comment]
Initially, I passed in this.state to calculateScrollCenter instead of the scene.appState, but I'm not aware of what implications that has with my current exposure to this project. I decided to leave it as is and modify only the width and height.
